---

- name: Update apt package cache
  apt:
    update_cache: yes

- name: Install MySQL Server
  apt:
    name: mysql-server
    state: present

- name: Set MySQL root password
  become: true
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_unix_socket: yes
  when: "'mysql_root_password' is defined"

- name: Create MySQL User
  become: true
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_user_password }}"
    host: localhost
    login_unix_socket: yes
  when: "'mysql_user' is defined and 'mysql_user_password' is defined"

- name: Grant privileges to the MySQL User
  become: true
  mysql_user:
    name: "{{ mysql_user }}"
    priv: "*.*:ALL"
    host: localhost
    login_unix_socket: yes
  when: "'mysql_user' is defined and 'mysql_user_password' is defined"
